# fly.toml app configuration file generated for eriza on 2023-06-18T12:47:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "eriza"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[http_service]
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1

[env]