import random

class YaoiGenerator:
    elements = [
        "Un gars normal et un type qui est trop d4rk wololo",
        "Un gars normal et un gars qui est trop un fou dans sa tête wololo",
        "Un audacieux journaliste et un mafieux",
        "Un flic et un mafieux",
        "Deux lycéens",
        "Un démon et un exorciste (forcément chaste et réservé)",
        "Un vampire et un prêtre (forcément chaste et réservé) au catholicisme made in l'absence de documentation",
        "Un lecteur/joueur et le méchant du livre/jeu",
        "Un lecteur/joueur et le héros du livre/jeu",
        "Un détective et un tueur en série (mais un tueur très propre)",
        "Type qui a un pouvoir très fort mais qui le fait s'évanouir/l'affaiblit/le laisse vulnérable kyah/type très très fort",
        "Jeune héritier gâté/son garde du corps qui est le seul à lui dire non",
        "Dans la forêt du yaoi, un type-lapin (ou mouton, ou souris, ou autre proie)/un type-prédateur (loup, ours, etc.) (réplique obligatoire : 'il va me manger >o<')",
        "Type normal/fantôme sexy de yaoi",
        "Délinquant au grand cœur/Délinquant au grand cœur aussi",
        "Bad boy mais pas trop/Délinquant au cœur très pur qui veut le vaincre un jour",
        "Amis d'enfance",
        "L'infirmier du lycée (forcément très sexy et séducteur)/n'importe qui",
        "Docteur sexy et séducteur/patient tout troublé",
        "Type normal/Le gars auquel il a rendu service dans leur enfance et qui l'aime depuis (mais Type a tout oublié)",
        "Type normal/son amie d'enfance de l'île où il passait ses vacances, et qui était en fait un homme !!",
        "Type normal/son ami d'enfance auquel il a promis le mariage, et qui n'a jamais oublié",
        "Un homme mûr et réservé et l'homme plus jeune qui l'aime !!§§",
        "Un homme mûr et tellement introverti qu'il a des lunettes + un jeune délinquant/host/etc.",
        "Un professeur qui a l'air d'un ado/un élève qui a l'air d'un adulte",
        "Un boss sexy et harceleur sexuel/son subordonné qui est tout troublé doudidonc",
        "Un boss sévère et très sec ): /son subordonné qui sait que ses remarques sont là pour qu'il s'améliore !!",
        "Un boss sévère et très sec ): /son subordonné qui est le seul à dire NON et qui a les yeux purs, toussa",
        "Type avec une profession douce (fleuriste, pâtissier, etc.) qui est secrètement un ancien délinquant et trop badass/Délinquant qui va clairement finir uke",
        "Sacrifice de monde pseudo-fantasy qui consent pour aider tout le monde <3/Le dieu sexy auquel il devait être sacrifié (le sacrifice doit mettre trente ans à comprendre qu'il ne va pas finir bouffé/tué)",
        "Héritier très recherché/type qui remplace sa sœur qui devait épouser l'héritier-mais-elle-s'est-cassée-bouhouhou et personne n'a remarqué qu'il n'était pas une femme",
        "Riche mafieux/type qu'un ou des membres de sa famille ont laissé avec de terribles dettes envers la mafia",
        "Type normal/succube incompétente kyah >o<",
        "Type normal/son animal de compagnie qui est devenu un bishonen sexy avec des oreilles de chien",
        "Amis d'enfance ultra fusionnels et tendres ensemble, mais personne n'a compris dans leur famille ou leur entourage",
        "Le serviteur secrètement amoureux de son maître riche héritier/son maître",
        "Ado/son demi-frère, mais en réalité c'est le fils de son beau-frère/sa belle-sœur dont c'est pas de l'inceste",
        "Type inconscient dans la rue/le type qui le ramasse",
        "Type qui se fait passer pour une femme en étant cis/type abusé par le subterfuge",
        "Auteur à succès avec un caractère acariâtre/Type qui l'admire >o<",
        "Auteur à succès qui doit écrire une scène de fesse et est prêt à beaucoup pour l'art/Assistant, éditeur ou fan qui veut aider",
        "Kabedon",
        "Réplique : [face à la confession d'un homme adulte mais plus jeune] Tu es trop jeune pour ce genre de déclaration",
        "Réplique : [face à la confession de quelqu'un de beaucoup plus jeune] Il ne faut pas faire ce genre de blagues à un homme de mon âge",
        "Je suis désolé, mais je ne peux plus m'arrêter",
        "Le fameux corps qui dit oui",
        "Le méchant qui passe sa vie à ne pas faire de trucs de méchant",
        "Le héros est le premier à dire non à son futur amoureux, pourtant riche/enfant gâté !! Choc du futur amoureux",
        "Oh là là, j'ai accidentellement bu cet aphrodisiaque/un méchant me l'a fait boire, oh là làààà",
        "Le héros traîné dans un hangar par de vils vilains qui veulent abuser de sa vertu ; son amoureux le sauve",
        "La meilleure amie ou l'ex-rivale romantique devenue entremetteuse",
        "L'ex qui cause un malentendu et angst ): ",
        "Le héros qui dit que ce n'est pas sa première fois pour rendre le seme jaloux ; le seme sait que c'est faux mais fait semblant de le prendre au sérieux pour lui apprendre à mentir hohoho, donc commence à le molester",
        "Le héros qui dit que ce n'est pas sa première fois pour rendre le seme jaloux ; le seme le prend au sérieux et est jaloux, donc commence à le molester",
        '"Il va me manger ! >o<" mais en fait, c\'était au sens yaoi du terme',
        "Résolution de ne jamais révéler ses sentiments ; révélation desdits sentiments par le scénar à la scène suivante",
        "Perso 1 est amnésique ; Perso 2 cède à la tentation et lui font croire qu'ils sortaient ensemble",
        "Perso 1 doit s'habiller en femme parce que [raison] (maid café pour la fin d'année, pièce de théâtre, pari, etc.) ; Pero 2 en est toute chose",
        "Le uke n'avait pas compris qu'ils sortaient ensemble depuis x temps",
        "Type normal/Être surnaturel auquel il avait oublié qu'il avait promis le mariage dans leur enfance",
        "Yokai ou divinité surpuissante/moine au cœur pur (avec ou sans cheveux)",
        "Suite à une dispute avec le seme, le uke furieux part prouver qu'il est un strong independant uke et se fait promptement molester",
        "\"Je ne ressens pas du tout la même chose quand Jean-Bob me touche et quand ce gredin me touche !\" *épiphanie*",
        "Le seme qui fait croire au uke qu'il a bu de l'aphrodisiaque, et ça marche",
        "Un homme-animal quelconque qui entre en chaleur alors qu'il est mâle",
        "Un objet imprévu rentre dans un trou prévu"
    ]

    def return_random_prompt():
        return random.choice(YaoiGenerator.elements)

    def return_random_prompts():
        return random.choices(YaoiGenerator.elements, 3)